name: char_project
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  firebase_auth: ^3.4.1
  firebase_core: ^1.19.1
  cloud_firestore: ^3.2.1
  lottie: ^1.3.0
  image_picker: ^0.8.5
  google_sign_in: ^5.4.0
  shared_preferences: ^2.0.15
  flutter_signin_button: ^2.0.0
  random_string: ^2.3.1
 
dev_dependencies: 
  flutter_lints: ^2.0.0
  lints: 2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
   
   - assets/lottie/23640-sign-in-or-sign-up-animation.json
   - assets/lottie/106364-login.json
   - assets/lottie/90397-log-in.json
   - assets/images/avatar.png